### ISSUE TITLE
mix.combine() does not get version hash

### ISSUE THREAD

**Issue by wolfgang42** [ctf0/laravel-mix-versionhash#10]
I'm using mix.combine() to concatenate some assets together that don't require any other processing. The resulting file is given a version id by `mix.version()`, but `mix.versionHash()` doesn't put a hash in the filename the way it does with `.sass()` or `.js()`.

**Comment by ctf0** [comment]
can u show me an example ?

**Comment by wolfgang42** [comment]
Sure:

```javascript
let mix = require('laravel-mix');
require('laravel-mix-versionhash');

mix.combine([
	'resources/assets/js/raven.js',
	'resources/assets/js/matomo.js',
], 'public/assets/vendor.js');

mix.versionHash();
```

This just produces `public/assets/vendor.js`, with no hash. I expect it to be called `vendor.0ddba11.js` or so.

**Comment by wolfgang42** [comment]
Yes, with `mix.version()` I get `/assets/vendor.js?id=adbb94909b3fc35d0fee`.

**Comment by wolfgang42** [comment]
This still seems to be happening with the latest version. Has there been any progress on investigating this?

**Comment by ctf0** [comment]
i think with the latest changes from @Erutan409 🚀, it will be easier to fix it.

if you can plz give it a go maybe u can find a solution for it 👍

**Comment by Erutan409** [comment]
@wolfgang42 @ctf0 Sure - can either of you suggest how to stage this for testing a fix?

**Comment by Erutan409** [comment]
Hmm...  So, there's a little bit of an issue, here.  Took me a while to track down what's happening, but here it goes:

1. The intention is to load the plugin via the [`--config`](https://webpack.js.org/configuration/#use-different-config-file) option with webpack, which points to [this file](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/setup/webpack.config.js).
2. The compilation of the overall webpack file is derived from the [`.build()` method](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/builder/WebpackConfig.js#L20-L26), which [adds the task](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/tasks/ConcatenateFilesTask.js) that takes care of concatenation with [.combine()](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/components/Combine.js#L48-L50), but is executed [after loading the user's webpack.mix.json file](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/setup/webpack.config.js#L27).
3. [This plugin](https://github.com/ctf0/laravel-mix-versionhash/blob/f9ecd67aeccbc8f00a13bb94ae1b96af67309675/src/index.js#L30-L40) is using the [chunkFilename](https://webpack.js.org/configuration/output/#outputchunkfilename), which means that the file from combine is [not being hashed](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/webpackPlugins/CustomTasksPlugin.js#L39) like the others are.

I even changed some of the code to be loaded as a [Task](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/tasks/Task.js) that was added on the ['loading-plugins' event](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/builder/WebpackConfig.js#L103) and confirmed that this plugin was executing its logic after all the other tasks that were previously loaded and executed.  This didn't matter because of the aforementioned reliance on hashing from webpack, itself.

Uhm...I'm not sure how to proceed with this one.  I mean - you could add your own arbitrary hash just to bust cache.  But, that probably wouldn't be ideal.  I'm guessing this is why laravel mix was initially designed to only suffix the filename with a query string since the combine is using [concatenate](https://github.com/stephenmathieson-boneyard/node-concatenate/blob/0.0.2/lib/concatenate.js#L115-L132).

I'm not intimately familiar with webpack as a whole, yet.  So, I'm curious if these types of assets can be piped through it, using its hashing capabilities, like the codebase is already doing.  Any ideas?

**Comment by Erutan409** [comment]
I'll look more into [this](https://survivejs.com/webpack/optimizing/adding-hashes-to-filenames/) later.

**Comment by ctf0** [comment]
@Erutan409  if its too big of a deal we can ignore it for now until we have a better understanding of webpack

**Comment by Erutan409** [comment]
How do you feel about crypto hashing and taking out the chunk hashing functionality in webpack?

It would make all hashing consistent.

**Comment by ctf0** [comment]
i prefer to stick as close as possible to the webpack system, so its easier for maintainability or what do u think ?

**Comment by Erutan409** [comment]
Well, [crypto](https://nodejs.org/api/crypto.html#crypto_crypto) is part of node core.  And after looking at [gulp-rev](https://github.com/sindresorhus/gulp-rev), which I've used in other build scenarios, it eventually [makes its way](https://github.com/sindresorhus/rev-hash/blob/master/index.js) to crypto in order to hash the file names.

Arguably, this could be a much simpler solution for all cases.

**Comment by ctf0** [comment]
okay then, lets go with it 👍

**Comment by Erutan409** [comment]
@wolfgang42 Quick question for you:

For you use case, when you create a new file with combine from 2+ files, how are you including them into your app?  Do you statically set a tag in head tag or is your other JS functionality pulling it in dynamically?

Trying to get a better understanding of how this hashing should account for the various loaders restructuring import name change(s); if at all in this scenario.

If I was going to use the combine functionality, my first thought would be to assume that you wouldn't/couldn't anticipate the other generated asset(s) knowing how to include the aforementioned and I'd have to account for it myself.

**Comment by ctf0** [comment]
i think what the combine does is it basically copy the content of first file to the next and save it into a new file

**Comment by wolfgang42** [comment]
@Erutan409 
> when you create a new file with combine from 2+ files, how are you including them into your app?

Just with a call to `mix('/assets/esmi.js')` in a static script tag. The reason I'm using combine() is because the app only needs a little bit of JS for a few things, so I'm using it as an extremely lightweight bundler that just joins together the JS files for each feature into a single file.

**Comment by aschanMarcus** [comment]
I also stumbled upon this issue and don't get any hashes with combine.
```
"laravel-mix": "^5.0.4",
"laravel-mix-versionhash": "^1.1.6",
```
```
mix.combine(['web/assets/css/_*.css'], 'web/assets/css/app.css')
mix.versionHash({length: 16})
```
It seems that `proxyMethod.before(Mix, 'addTask', (task) => {})` isn't triggered. Looping through `Mix.tasks` seems to work.

**Comment by ctf0** [comment]
@aschanMarcus can u send a PR with the fix ?

**Comment by andresgutgon** [comment]
@ahmedmaazin your fix looks good but with my configuration is not working:
``` javascript
const mix = require('laravel-mix');
const atImport = require('postcss-import');
const tailwindcss = require('tailwindcss');

mix
  .setPublicPath('./dist')
  .sass('assets/css/tailwindcss_utilities.scss', 'css')
  .sass('assets/css/blog.scss', 'css')
  .options({
    processCssUrls: false, // Put images in CSS relative to generated CSS
    postCss: [
      atImport(),
      tailwindcss('tailwind.config.js'),
      require('autoprefixer')
    ],
  })
  .js('assets/js/blog.js', 'js')
  .combine(
    [
      'dist/css/tailwindcss_utilities.css',
      'dist/css/blog.css'
    ],
    'dist/css/styles.css'
  )

if (mix.inProduction()) {
  require('laravel-mix-versionhash');
  // Cache busting only in production. Ex.: /css/blog-8e5c48eadbfdd5458ec6.js
  mix.versionHash()
}
```

So `assets` is empty `[]`

![image](https://user-images.githubusercontent.com/49499/101984404-91d47600-3c81-11eb-8258-bf5ee697519a.png)
